using AbfDB.Databases;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace AbfDB
{
    public static class DatabaseBuilder
    {
        public static void Build(string scanFolder, string outputFolder = "./")
        {
            AbfDatabase[] databases = {
                new CsvDatabase("abfdb.csv"),
                new SqliteDatabase("abfdb.sqlite"),
            };

            AddAbfs(scanFolder, databases);
        }

        /// <summary>
        /// Recursively scan the search folder for ABFs and add their records to each database given
        /// </summary>
        private static void AddAbfs(string searchFolder, AbfDatabase[] databases)
        {
            Log(string.Concat(Enumerable.Repeat("#", 80)));
            Log($"[{DateTime.Now}] Starting scan: {searchFolder}");

            Stopwatch stopwatch = Stopwatch.StartNew();
            int AbfsRead = 0;

            foreach (string relativePath in Directory.EnumerateFiles(searchFolder, "*.abf", SearchOption.AllDirectories))
            {
                if (relativePath.EndsWith(".abf") == false) // fixes a bug in .NET Framework that's not in .NET Core
                    continue;
                string fullPath = Path.GetFullPath(relativePath);

                try
                {
                    AbfSharp.ABFFIO.ABF abf = new(fullPath);
                    AbfRecord record = new()
                    {
                        FullPath = fullPath,
                        Episodes = abf.Header.lActualEpisodes,
                        Date = abf.Header.uFileStartDate,
                        Time = abf.Header.uFileStartTimeMS,
                        Stopwatch = abf.Header.lStopwatchTime,
                        FileHashMD5 = GetMD5Hash(fullPath),
                    };

                    foreach (AbfDatabase database in databases)
                        database.Add(record);

                    AbfsRead += 1;
                    Console.WriteLine($"ABFs={AbfsRead} Elapsed={stopwatch.Elapsed} Path={fullPath}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"EXCEPTION: see log file for details");
                    Log($"\nEXCEPTION: {fullPath}\n{ex}\n");
                }
            }

            Log($"[{DateTime.Now}] Scan finished: Read {AbfsRead} ABFs in {stopwatch.Elapsed}");
        }

        /// <summary>
        /// Log a message to the given text file
        /// </summary>
        private static void Log(string message, string logFilePath = "log.txt")
        {
            using StreamWriter writer = File.AppendText(logFilePath);
            writer.WriteLine(message);
        }

        /// <summary>
        /// Return the MD5 hash for a file on the filesystem.
        /// Hashes are identical to those generated by the CertUtil command.
        /// </summary>
        private static string GetMD5Hash(string filePath)
        {
            var md5 = MD5.Create();
            using var stream = File.OpenRead(filePath);
            return string.Join("", md5.ComputeHash(stream).Select(x => x.ToString("x2")));
        }
    }
}
